### ISSUE TITLE
Question: How to connect per RDP over a SOCKS server?

### ISSUE THREAD

**Issue by maglub** [royalapplications/royalapps-community-freerdp#14]
Hi,

Is there a way to define a SOCKS server as a jump host?

Have a nice day!
//magnus

**Comment by StefanKoell** [comment]
I'm not entirely sure. According to the docs there are currently no command line switches available to set that:
https://github.com/FreeRDP/FreeRDP/wiki/CommandLineInterface

I'm also not sure if this is kept updated. Some switches I use are not on that list. I will investigate...
